github:
  release: true
  releaseName: "v${version}"
npm:
  ignoreVersion: true
  publish: false
git:
  requireCleanWorkingDir: false
  tagName: "v${version}"
  addUntrackedFiles: true
hooks:
  "before:init":
    - "git config --global user.email \"pipeline@github.com\"; git config --global user.name \"Github pipeline\""
